name: Continuous Integration
on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build -PignoreCheckFailures=true

      - name: Test Report
        uses: scacap/action-surefire-report@v1.0.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          report_paths: ./build/test-results/test/*.xml

      - name: Archive build output
        uses: actions/upload-artifact@v1
        with:
          name: gradle-build
          path: build
